name: "🚫 TSML team only"
description: "This form is only for the Code for Recovery TSML team"
body:
  - type: markdown
    attributes:
      value: |
        ✋🛑 Stop! This form is only for the Code for Recovery TSML team - please [Create a Discussion](https://github.com/code4recovery/12-step-meeting-list/discussions/new?category=q-a) to get help from our support rotation.
  - type: textarea
    attributes:
      label: "Add a description"
    validations:
      required: true
      