<?php
/*	
don't make changes! it'll make staying updated much harder.
for updates / questions, please contact web@aasanjose.org
*/

//custom post types
if (!defined('TSML_TYPE_MEETINGS'))  define('TSML_TYPE_MEETINGS',  'meetings');
if (!defined('TSML_TYPE_LOCATIONS')) define('TSML_TYPE_LOCATIONS', 'locations');
if (!defined('TSML_TYPE_GROUPS'))    define('TSML_TYPE_GROUPS',    'tsml_group');
if (!defined('GROUP_CONTACT_COUNT')) define('GROUP_CONTACT_COUNT', 3); //number of contacts per group

$tsml_alerts = array();

$tsml_days	= array(
	0 => array(0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml')),
	1 => array(1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml')),
	2 => array(2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml')),
	3 => array(3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml')),
	4 => array(4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml')),
	5 => array(5=>__('Friday', 'tsml'), 6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml')),
	6 => array(6=>__('Saturday', 'tsml'), 0=>__('Sunday', 'tsml'), 1=>__('Monday', 'tsml'), 2=>__('Tuesday', 'tsml'), 3=>__('Wednesday', 'tsml'), 4=>__('Thursday', 'tsml'), 5=>__('Friday', 'tsml')),
);

$tsml_days = $tsml_days[get_option('start_of_week', 0)];

$tsml_days_order = array_keys($tsml_days); //used by tsml_meetings_sort() over and over

$tsml_nonce = plugin_basename(__FILE__);

$tsml_program = get_option('tsml_program', 'aa');

$tsml_programs = array(
	'al-anon'	=> __('Al-Anon', 'tsml'),
	'aa'		=> __('Alcoholics Anonymous', 'tsml'),
	'coda'		=> __('Co-Dependents Anonymous', 'tsml'),
	'na'		=> __('Narcotics Anonymous', 'tsml'),
	'oa'		=> __('Overeaters Anonymous', 'tsml'),
	'sa'		=> __('Sexaholics Anonymous', 'tsml'),
	'saa'		=> __('Sex Addicts Anonymous', 'tsml'),
	'slaa'		=> __('Sex and Love Addicts Anonymous', 'tsml'),
);

$tsml_regions = array();

$tsml_types = array(
	'aa' => array(
		'A'		=> __('Atheist / Agnostic', 'tsml'),
		'BA'	=> __('Babysitting Available', 'tsml'),
		'BE'	=> __('Beginner', 'tsml'),
		'B'		=> __('Big Book', 'tsml'),
		'CF'	=> __('Child-Friendly', 'tsml'),
		'H'		=> __('Chips', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'CAN'	=> __('Candlelight', 'tsml'),
		'AL-AN'	=> __('Concurrent with Al-Anon', 'tsml'),
		'AL'	=> __('Concurrent with Alateen', 'tsml'),
		'XT'	=> __('Cross Talk Permitted', 'tsml'),
		'DLY'	=> __('Daily', 'tsml'),
		'FF'	=> __('Fragrance Free', 'tsml'),
		'FR'	=> __('French', 'tsml'),
		'G'		=> __('Gay', 'tsml'),
		'GR'	=> __('Grapevine', 'tsml'),
		'L'		=> __('Lesbian', 'tsml'),
		'LIT'	=> __('Literature', 'tsml'),
		'LGBTQ'	=> __('LGBTQ', 'tsml'),
		'MED'	=> __('Meditation', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'ASL'	=> __('Sign Language', 'tsml'),
		'SM'	=> __('Smoking Permitted', 'tsml'),
		'S'		=> __('Spanish', 'tsml'),
		'SP'	=> __('Speaker', 'tsml'),
		'ST'	=> __('Step Meeting', 'tsml'),
		'D'		=> __('Topic Discussion', 'tsml'),
		'TR'	=> __('Tradition', 'tsml'),
		'T'		=> __('Transgender', 'tsml'),
		'X'		=> __('Wheelchair Accessible', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
		'Y'		=> __('Young People', 'tsml'),
	),
	'al-anon' => array(
		'AC'	=> __('Adult Child Focus', 'tsml'),
		'Y'		=> __('Alateen', 'tsml'),
		'A'		=> __('Atheist / Agnostic', 'tsml'),
		'BA'	=> __('Babysitting Available', 'tsml'),
		'BE'	=> __('Beginner', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'AA'	=> __('Concurrent with AA Meeting', 'tsml'),
		'AL'	=> __('Concurrent with Alateen Meeting', 'tsml'),
		'FF'	=> __('Fragrance Free', 'tsml'),
		'G'		=> __('Gay', 'tsml'),
		'L'		=> __('Lesbian', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'S'		=> __('Spanish', 'tsml'),
		'SP'	=> __('Speaker', 'tsml'),
		'ST'	=> __('Step Meeting', 'tsml'),
		'T'		=> __('Transgender', 'tsml'),
		'X'		=> __('Wheelchair Accessible', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
	),
	'coda' => array(
		'A'		=> __('Atheist / Agnostic', 'tsml'),
		'BA'	=> __('Babysitting Available', 'tsml'),
		'BE'	=> __('Beginner', 'tsml'),
		'B'		=> __('Book Study', 'tsml'),
		'CF'	=> __('Child-Friendly', 'tsml'),
		'H'		=> __('Chips', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'CAN'	=> __('Candlelight', 'tsml'),
		'AL-AN'	=> __('Concurrent with Al-Anon', 'tsml'),
		'AL'	=> __('Concurrent with Alateen', 'tsml'),
		'XT'	=> __('Cross Talk Permitted', 'tsml'),
		'DLY'	=> __('Daily', 'tsml'),
		'FF'	=> __('Fragrance Free', 'tsml'),
		'G'		=> __('Gay', 'tsml'),
		'GR'	=> __('Grapevine', 'tsml'),
		'L'		=> __('Lesbian', 'tsml'),
		'LIT'	=> __('Literature', 'tsml'),
		'LGBTQ'	=> __('LGBTQ', 'tsml'),
		'MED'	=> __('Meditation', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'QA'	=> __('Q & A', 'tsml'),
		'READ' 	=> __('Reading', 'tsml'),
		'SHARE'	=> __('Sharing', 'tsml'),
		'ASL'	=> __('Sign Language', 'tsml'),
		'SM'	=> __('Smoking Permitted', 'tsml'),
		'S'		=> __('Spanish', 'tsml'),
		'SP'	=> __('Speaker', 'tsml'),
		'ST'	=> __('Step Meeting', 'tsml'),
		'TEEN'	=> __('Teens Only', 'tsml'),
		'D'		=> __('Topic Discussion', 'tsml'),
		'TR'	=> __('Tradition', 'tsml'),
		'T'		=> __('Transgender', 'tsml'),
		'X'		=> __('Wheelchair Accessible', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
		'WRITE'	=> __('Writing', 'tsml'),
		'Y'		=> __('Young People', 'tsml'),
	),
	'na' => array(
		'CPT'	=> __('12 Concepts', 'tsml'),
		'BT'	=> __('Basic Text', 'tsml'),
		'BEG'	=> __('Beginner/Newcomer', 'tsml'),
		'CAN'	=> __('Candlelight', 'tsml'),
		'CW'	=> __('Children Welcome', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'DISC'	=> __('Discussion/Participation', 'tsml'),
		'GL'	=> __('Gay/Lesbian', 'tsml'),
		'IP'	=> __('IP Study', 'tsml'),
		'IW'	=> __('It Works Study', 'tsml'),
		'JFT'	=> __('Just For Today Study', 'tsml'),
		'LIT'	=> __('Literature Study', 'tsml'),
		'LC'	=> __('Living Clean', 'tsml'),
		'M'		=> __('Men', 'tsml'),
		'MED'	=> __('Meditation', 'tsml'),
		'NS'	=> __('Non-Smoking', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'QA'	=> __('Questions & Answers', 'tsml'),
		'RA'	=> __('Restricted Access', 'tsml'),
		'SMOK'	=> __('Smoking', 'tsml'),
		'SPK'	=> __('Speaker', 'tsml'),
		'STEP'	=> __('Step', 'tsml'),
		'SWG'	=> __('Step Working Guide Study', 'tsml'),
		'TOP'	=> __('Topic', 'tsml'),
		'TRAD'	=> __('Tradition', 'tsml'),
		'VAR'	=> __('Format Varies', 'tsml'),
		'X'		=> __('Wheelchair Accessible', 'tsml'),
		'W'		=> __('Women', 'tsml'),
		'Y'		=> __('Young People', 'tsml'),
	),
	'oa' => array(
		'11TH'  => __('11th Step', 'tsml'),
		'90D'   => __('90 Day', 'tsml'),
		'AA12'  => __('AA 12/12', 'tsml'),
		'AIB'   => __('Ask-It-Basket', 'tsml'),
		'B'     => __('Big Book', 'tsml'),
		'DOC'   => __('Dignity of Choice', 'tsml'),
		'FT'    => __('For Today', 'tsml'),
		'LI'    => __('Lifeline', 'tsml'),
		'LIS'   => __('Lifeline Sampler', 'tsml'),
		'LIT'   => __('Literature Study', 'tsml'),
		'MAIN'  => __('Maintenance', 'tsml'),
		'MED'   => __('Meditation', 'tsml'),
		'NEWB'  => __('New Beginnings', 'tsml'),
		'BE'    => __('Newcomer', 'tsml'),
		'HOW'   => __('OA H.O.W.', 'tsml'),
		'OA23'  => __('OA Second and/or Third Edition', 'tsml'),
		'ST'    => __('OA Steps and/or Traditions Study', 'tsml'),
		'RELA'  => __('Relapse/12th Step Within', 'tsml'),
		'SSP'   => __('Seeking the Spiritual Path', 'tsml'),
		'SP'    => __('Speaker', 'tsml'),
		'SD'    => __('Speaker/Discussion', 'tsml'),
		'SPIR'  => __('Spirituality', 'tsml'),
		'TEEN'  => __('Teen Friendly', 'tsml'),
		'PROM'  => __('The Promises', 'tsml'),
		'TOOL'  => __('Tools', 'tsml'),
		'D'     => __('Topic', 'tsml'),
		'MISC'  => __('Varies', 'tsml'),
		'VOR'   => __('Voices of Recovery', 'tsml'),
		'WORK'  => __('Work Book Study', 'tsml'),
		'WRIT'  => __('Writing', 'tsml'),
	),	
	'sa' => array(
		'BE'	=> __('Beginner', 'tsml'),
		'B'		=> __('Book Study', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'MED'	=> __('Meditation', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'MI'	=> __('Mixed', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'PP'	=> __('Primary Purpose', 'tsml'),
		'SP'	=> __('Speaker', 'tsml'),
		'ST'	=> __('Step Study', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
	),
	'saa' => array(
		'C'		=> __('Closed', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'ST'	=> __('Step Meeting', 'tsml'),
		'LGBTQ'	=> __('LGBTQ', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
	),
	'slaa' => array(
		'AN'	=> __('Anorexia Focus', 'tsml'),
		'B'		=> __('Book Study', 'tsml'),
		'H'		=> __('Chips', 'tsml'),
		'BA'	=> __('Child Care Available', 'tsml'),
		'C'		=> __('Closed', 'tsml'),
		'FF'	=> __('Fragrance Free', 'tsml'),
		'GC'	=> __('Getting Current', 'tsml'),
		'X'		=> __('Handicapped Accessible', 'tsml'),
		'HR'	=> __('Healthy Relationships', 'tsml'),
		'LIT'	=> __('Literature Reading', 'tsml'),
		'MED'	=> __('Meditation', 'tsml'),
		'M'		=> __('Men Only', 'tsml'),
		'NC'	=> __('Newcomers', 'tsml'),
		'O'		=> __('Open', 'tsml'),
		'PRI'	=> __('Prison', 'tsml'),
		'S'		=> __('Spanish', 'tsml'),
		'SP'	=> __('Speaker', 'tsml'),
		'ST'	=> __('Step Study', 'tsml'),
		'D'		=> __('Topic Discussion', 'tsml'),
		'TR'	=> __('Tradition Study', 'tsml'),
		'W'		=> __('Women Only', 'tsml'),
	),
);

$tsml_types_in_use = get_option('tsml_types_in_use', array_keys($tsml_types[$tsml_program]));
if (!is_array($tsml_types_in_use)) $tsml_types_in_use = array();